from __future__ import annotations

import hashlib
import json
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional


FIXTURE_SOURCE_VERSION = "fixture-v2"


def _ts(now_utc: datetime, age_seconds: int = 0) -> str:
    return (now_utc - timedelta(seconds=age_seconds)).isoformat()


def _verified(now_utc: datetime, age_hours: int = 0) -> str:
    return (now_utc - timedelta(hours=age_hours)).isoformat()


def load_fixture_universe(reference_utc: Optional[datetime] = None) -> Dict[str, Any]:
    now_utc = reference_utc or datetime.now(timezone.utc)
    listings: List[Dict[str, Any]] = [
        {
            "company_name": "Reliance Industries Limited",
            "isin": "INE002A01018",
            "sector": "Energy",
            "industry": "Integrated Oil & Gas",
            "market_cap_category": "LARGE_CAP",
            "symbol": "RELIANCE",
            "trading_symbol": "RELIANCE",
            "exchange": "NSE",
            "segment": "CASH",
            "instrument_type": "EQUITY",
            "underlying_symbol": "RELIANCE",
            "lot_size": 1,
            "tick_size": 0.05,
            "price_precision": 2,
            "fno_eligible": True,
            "cash_eligible": True,
            "currency": "INR",
            "active": True,
            "listing_date": "1995-01-01",
            "nse_symbol": "RELIANCE",
            "mappings": {
                "fyers": {"broker_symbol": "NSE:RELIANCE-EQ", "exchange_token": "2885", "last_verified_age_hours": 2},
                "dhan": {"broker_symbol": "RELIANCE", "broker_security_id": "1333", "last_verified_age_hours": 2},
            },
            "quote": {
                "source": "FIXTURE",
                "ltp": 2500.50,
                "open": 2475.0,
                "high": 2518.0,
                "low": 2462.5,
                "previous_close": 2469.0,
                "bid": 2500.0,
                "ask": 2501.0,
                "bid_quantity": 35000,
                "ask_quantity": 32000,
                "volume": 1_250_000,
                "traded_value": 3_126_000_000.0,
                "vwap": 2496.4,
                "open_interest": 0,
                "change_in_oi": 0,
                "data_mode": "FIXTURE",
                "sequence_number": 101,
                "age_seconds": 3,
            },
        },
        {
            "company_name": "Reliance Industries Limited",
            "isin": "INE002A01018",
            "sector": "Energy",
            "industry": "Integrated Oil & Gas",
            "market_cap_category": "LARGE_CAP",
            "symbol": "RELIANCE",
            "trading_symbol": "500325",
            "exchange": "BSE",
            "segment": "CASH",
            "instrument_type": "EQUITY",
            "underlying_symbol": "RELIANCE",
            "lot_size": 1,
            "tick_size": 0.05,
            "price_precision": 2,
            "fno_eligible": True,
            "cash_eligible": True,
            "currency": "INR",
            "active": True,
            "listing_date": "1995-01-01",
            "bse_code": "500325",
            "mappings": {
                "fyers": {"broker_symbol": "BSE:500325", "exchange_token": "500325", "last_verified_age_hours": 2},
                "dhan": {"broker_symbol": "RELIANCE-BSE", "broker_security_id": "5333", "last_verified_age_hours": 2},
            },
            "quote": {
                "source": "FIXTURE",
                "ltp": 2499.70,
                "open": 2478.0,
                "high": 2508.0,
                "low": 2468.0,
                "previous_close": 2472.0,
                "bid": 2498.5,
                "ask": 2502.5,
                "bid_quantity": 6000,
                "ask_quantity": 5500,
                "volume": 225_000,
                "traded_value": 562_500_000.0,
                "vwap": 2492.1,
                "open_interest": 0,
                "change_in_oi": 0,
                "data_mode": "FIXTURE",
                "sequence_number": 102,
                "age_seconds": 7,
            },
        },
        {
            "company_name": "Reliance Industries Limited",
            "isin": "INE002A01018",
            "sector": "Energy",
            "industry": "Integrated Oil & Gas",
            "market_cap_category": "LARGE_CAP",
            "symbol": "RELIANCE",
            "trading_symbol": "RELIANCE26AUGFUT",
            "exchange": "NSE",
            "segment": "FNO",
            "instrument_type": "FUTURE",
            "underlying_symbol": "RELIANCE",
            "expiry": "2026-08-27",
            "lot_size": 250,
            "tick_size": 0.05,
            "price_precision": 2,
            "fno_eligible": True,
            "cash_eligible": False,
            "currency": "INR",
            "active": True,
            "listing_date": "2026-07-01",
            "nse_symbol": "RELIANCE",
            "mappings": {
                "fyers": {"broker_symbol": "NSE:RELIANCE26AUGFUT", "exchange_token": "2885-FUT", "last_verified_age_hours": 2},
                "dhan": {"broker_symbol": "RELIANCE AUG FUT", "broker_security_id": "1444", "last_verified_age_hours": 2},
            },
            "quote": {
                "source": "FIXTURE",
                "ltp": 2512.0,
                "open": 2488.0,
                "high": 2522.5,
                "low": 2479.0,
                "previous_close": 2483.0,
                "bid": 2511.5,
                "ask": 2512.5,
                "bid_quantity": 9000,
                "ask_quantity": 8500,
                "volume": 21000,
                "traded_value": 52_760_000.0,
                "vwap": 2508.2,
                "open_interest": 310000,
                "change_in_oi": 12000,
                "data_mode": "FIXTURE",
                "sequence_number": 103,
                "age_seconds": 4,
            },
        },
        {
            "company_name": "Reliance Industries Limited",
            "isin": "INE002A01018",
            "sector": "Energy",
            "industry": "Integrated Oil & Gas",
            "market_cap_category": "LARGE_CAP",
            "symbol": "RELIANCE",
            "trading_symbol": "RELIANCE28AUG3000CE",
            "exchange": "NSE",
            "segment": "FNO",
            "instrument_type": "OPTION",
            "underlying_symbol": "RELIANCE",
            "expiry": "2026-08-27",
            "strike": 3000.0,
            "option_type": "CE",
            "lot_size": 250,
            "tick_size": 0.05,
            "price_precision": 2,
            "fno_eligible": True,
            "cash_eligible": False,
            "currency": "INR",
            "active": True,
            "listing_date": "2026-07-01",
            "nse_symbol": "RELIANCE",
            "mappings": {
                "fyers": {"broker_symbol": "NSE:RELIANCE28AUG3000CE", "exchange_token": "2885-CE", "last_verified_age_hours": 2},
                "dhan": {"broker_symbol": "RELIANCE 3000 CE", "broker_security_id": "1445", "last_verified_age_hours": 2},
            },
            "quote": {
                "source": "FIXTURE",
                "ltp": 42.25,
                "open": 38.4,
                "high": 44.0,
                "low": 37.8,
                "previous_close": 39.2,
                "bid": 42.15,
                "ask": 42.30,
                "bid_quantity": 12000,
                "ask_quantity": 11500,
                "volume": 125000,
                "traded_value": 5_250_000.0,
                "vwap": 41.8,
                "open_interest": 8800,
                "change_in_oi": 500,
                "data_mode": "FIXTURE",
                "sequence_number": 104,
                "age_seconds": 5,
            },
        },
        {
            "company_name": "Zen Energy Limited",
            "isin": "INEZEN123456",
            "sector": "Utilities",
            "industry": "Power Generation",
            "market_cap_category": "MID_CAP",
            "symbol": "ZENENG",
            "trading_symbol": "ZENENG",
            "exchange": "NSE",
            "segment": "CASH",
            "instrument_type": "EQUITY",
            "underlying_symbol": "ZENENG",
            "lot_size": 1,
            "tick_size": 0.05,
            "price_precision": 2,
            "fno_eligible": False,
            "cash_eligible": True,
            "currency": "INR",
            "active": True,
            "listing_date": "2010-01-01",
            "nse_symbol": "ZENENG",
            "mappings": {
                "fyers": {"broker_symbol": "NSE:ZENENG-EQ", "exchange_token": "6001", "last_verified_age_hours": 6},
                "dhan": {"broker_symbol": "ZENENG", "broker_security_id": "6001", "last_verified_age_hours": 6},
            },
            "quote": {
                "source": "FIXTURE",
                "ltp": 185.0,
                "open": 180.0,
                "high": 186.0,
                "low": 179.0,
                "previous_close": 181.5,
                "bid": 184.0,
                "ask": 186.0,
                "bid_quantity": 800,
                "ask_quantity": 950,
                "volume": 8000,
                "traded_value": 1_480_000.0,
                "vwap": 183.2,
                "open_interest": 0,
                "change_in_oi": 0,
                "data_mode": "FIXTURE",
                "sequence_number": 105,
                "age_seconds": 8,
            },
        },
        {
            "company_name": "Zen Energy Limited",
            "isin": "INEZEN123456",
            "sector": "Utilities",
            "industry": "Power Generation",
            "market_cap_category": "MID_CAP",
            "symbol": "ZENENG",
            "trading_symbol": "540777",
            "exchange": "BSE",
            "segment": "CASH",
            "instrument_type": "EQUITY",
            "underlying_symbol": "ZENENG",
            "lot_size": 1,
            "tick_size": 0.05,
            "price_precision": 2,
            "fno_eligible": False,
            "cash_eligible": True,
            "currency": "INR",
            "active": True,
            "listing_date": "2010-01-01",
            "bse_code": "540777",
            "mappings": {
                "fyers": {"broker_symbol": "BSE:540777", "exchange_token": "540777", "last_verified_age_hours": 4},
                "dhan": {"broker_symbol": "ZENENG-BSE", "broker_security_id": "6077", "last_verified_age_hours": 4},
            },
            "quote": {
                "source": "FIXTURE",
                "ltp": 184.75,
                "open": 181.0,
                "high": 185.25,
                "low": 180.5,
                "previous_close": 181.0,
                "bid": 184.6,
                "ask": 184.9,
                "bid_quantity": 25000,
                "ask_quantity": 28000,
                "volume": 60000,
                "traded_value": 11_085_000.0,
                "vwap": 184.4,
                "open_interest": 0,
                "change_in_oi": 0,
                "data_mode": "FIXTURE",
                "sequence_number": 106,
                "age_seconds": 5,
            },
        },
        {
            "company_name": "Tata Consultancy Services Limited",
            "isin": "INE467B01029",
            "sector": "Technology",
            "industry": "IT Services",
            "market_cap_category": "LARGE_CAP",
            "symbol": "TCS",
            "trading_symbol": "TCS",
            "exchange": "NSE",
            "segment": "CASH",
            "instrument_type": "EQUITY",
            "underlying_symbol": "TCS",
            "lot_size": 1,
            "tick_size": 0.05,
            "price_precision": 2,
            "fno_eligible": False,
            "cash_eligible": True,
            "currency": "INR",
            "active": True,
            "listing_date": "2004-08-25",
            "nse_symbol": "TCS",
            "mappings": {
                "fyers": {"broker_symbol": "NSE:TCS-EQ", "exchange_token": "11536", "last_verified_age_hours": 3},
                "dhan": {},
            },
            "quote": {
                "source": "FIXTURE",
                "ltp": 4010.0,
                "open": 3980.0,
                "high": 4020.0,
                "low": 3972.0,
                "previous_close": 3975.0,
                "bid": 4009.0,
                "ask": 4011.0,
                "bid_quantity": 5200,
                "ask_quantity": 5100,
                "volume": 185000,
                "traded_value": 741_850_000.0,
                "vwap": 4005.5,
                "open_interest": 0,
                "change_in_oi": 0,
                "data_mode": "FIXTURE",
                "sequence_number": 107,
                "age_seconds": 6,
            },
        },
        {
            "company_name": "Bombay Paints Limited",
            "isin": "INEBPNT00012",
            "sector": "Materials",
            "industry": "Paints",
            "market_cap_category": "SMALL_CAP",
            "symbol": "BPAINT",
            "trading_symbol": "532000",
            "exchange": "BSE",
            "segment": "CASH",
            "instrument_type": "EQUITY",
            "underlying_symbol": "BPAINT",
            "lot_size": 1,
            "tick_size": 0.05,
            "price_precision": 2,
            "fno_eligible": False,
            "cash_eligible": True,
            "currency": "INR",
            "active": True,
            "listing_date": "2012-04-01",
            "bse_code": "532000",
            "mappings": {
                "fyers": {"broker_symbol": "BSE:532000", "exchange_token": "532000", "last_verified_age_hours": 30},
                "dhan": {"broker_symbol": "BPAINT-BSE", "broker_security_id": "7001", "last_verified_age_hours": 30},
            },
            "quote": {
                "source": "FIXTURE",
                "ltp": 78.0,
                "open": 77.5,
                "high": 79.0,
                "low": 76.0,
                "previous_close": 77.0,
                "bid": 75.0,
                "ask": 81.5,
                "bid_quantity": 40,
                "ask_quantity": 55,
                "volume": 900,
                "traded_value": 70_200.0,
                "vwap": 78.0,
                "open_interest": 0,
                "change_in_oi": 0,
                "data_mode": "FIXTURE",
                "sequence_number": 108,
                "age_seconds": 65,
            },
        },
        {
            "company_name": "Shared Consumer Limited",
            "isin": "INESHARE0001",
            "sector": "Consumer",
            "industry": "Staples",
            "market_cap_category": "SMALL_CAP",
            "symbol": "SHARED",
            "trading_symbol": "SHARED",
            "exchange": "NSE",
            "segment": "CASH",
            "instrument_type": "EQUITY",
            "underlying_symbol": "SHARED",
            "lot_size": 1,
            "tick_size": 0.05,
            "price_precision": 2,
            "fno_eligible": False,
            "cash_eligible": True,
            "currency": "INR",
            "active": True,
            "listing_date": "2018-01-01",
            "nse_symbol": "SHARED",
            "mappings": {
                "fyers": {"broker_symbol": "NSE:SHARED-EQ", "exchange_token": "8001", "last_verified_age_hours": 4},
                "dhan": {"broker_symbol": "SHARED", "broker_security_id": "8001", "last_verified_age_hours": 4},
            },
            "quote": {
                "source": "FIXTURE",
                "ltp": 210.0,
                "open": 208.0,
                "high": 212.0,
                "low": 206.5,
                "previous_close": 207.5,
                "bid": 209.5,
                "ask": 210.5,
                "bid_quantity": 2200,
                "ask_quantity": 2300,
                "volume": 15000,
                "traded_value": 3_150_000.0,
                "vwap": 209.2,
                "open_interest": 0,
                "change_in_oi": 0,
                "data_mode": "FIXTURE",
                "sequence_number": 109,
                "age_seconds": 5,
            },
        },
        {
            "company_name": "Shared Logistics Limited",
            "isin": "INESHARE0002",
            "sector": "Industrials",
            "industry": "Logistics",
            "market_cap_category": "SMALL_CAP",
            "symbol": "SHARED",
            "trading_symbol": "SHARED",
            "exchange": "BSE",
            "segment": "CASH",
            "instrument_type": "EQUITY",
            "underlying_symbol": "SHARED",
            "lot_size": 1,
            "tick_size": 0.05,
            "price_precision": 2,
            "fno_eligible": False,
            "cash_eligible": True,
            "currency": "INR",
            "active": True,
            "listing_date": "2018-01-01",
            "bse_code": "540888",
            "mappings": {
                "fyers": {"broker_symbol": "BSE:540888", "exchange_token": "540888", "last_verified_age_hours": 4},
                "dhan": {"broker_symbol": "SHARED-BSE", "broker_security_id": "8088", "last_verified_age_hours": 4},
            },
            "quote": {
                "source": "FIXTURE",
                "ltp": 212.5,
                "open": 210.0,
                "high": 214.0,
                "low": 209.0,
                "previous_close": 210.0,
                "bid": 211.5,
                "ask": 213.5,
                "bid_quantity": 1400,
                "ask_quantity": 1350,
                "volume": 9000,
                "traded_value": 1_912_500.0,
                "vwap": 212.0,
                "open_interest": 0,
                "change_in_oi": 0,
                "data_mode": "FIXTURE",
                "sequence_number": 110,
                "age_seconds": 5,
            },
        },
        {
            "company_name": "Lotus Health Limited",
            "isin": "INECONFLICT001",
            "sector": "Healthcare",
            "industry": "Hospitals",
            "market_cap_category": "MID_CAP",
            "symbol": "LOTUS",
            "trading_symbol": "LOTUS",
            "exchange": "NSE",
            "segment": "CASH",
            "instrument_type": "EQUITY",
            "underlying_symbol": "LOTUS",
            "lot_size": 1,
            "tick_size": 0.05,
            "price_precision": 2,
            "fno_eligible": False,
            "cash_eligible": True,
            "currency": "INR",
            "active": True,
            "listing_date": "2014-06-01",
            "nse_symbol": "LOTUS",
            "mappings": {
                "fyers": {"broker_symbol": "NSE:LOTUS-EQ", "exchange_token": "9001", "last_verified_age_hours": 2},
                "dhan": {"broker_symbol": "LOTUS", "broker_security_id": "9001", "last_verified_age_hours": 2},
            },
            "quote": {
                "source": "FIXTURE",
                "ltp": 512.0,
                "open": 505.0,
                "high": 514.0,
                "low": 503.0,
                "previous_close": 504.0,
                "bid": 511.5,
                "ask": 512.5,
                "bid_quantity": 3000,
                "ask_quantity": 3100,
                "volume": 42000,
                "traded_value": 21_504_000.0,
                "vwap": 511.0,
                "open_interest": 0,
                "change_in_oi": 0,
                "data_mode": "FIXTURE",
                "sequence_number": 111,
                "age_seconds": 4,
            },
        },
        {
            "company_name": "Coral Retail Limited",
            "isin": "INECONFLICT001",
            "sector": "Retail",
            "industry": "Department Stores",
            "market_cap_category": "MID_CAP",
            "symbol": "CORAL",
            "trading_symbol": "CORAL",
            "exchange": "BSE",
            "segment": "CASH",
            "instrument_type": "EQUITY",
            "underlying_symbol": "CORAL",
            "lot_size": 1,
            "tick_size": 0.05,
            "price_precision": 2,
            "fno_eligible": False,
            "cash_eligible": True,
            "currency": "INR",
            "active": True,
            "listing_date": "2014-06-01",
            "bse_code": "540999",
            "mappings": {
                "fyers": {"broker_symbol": "BSE:540999", "exchange_token": "540999", "last_verified_age_hours": 2},
                "dhan": {"broker_symbol": "CORAL", "broker_security_id": "9099", "last_verified_age_hours": 2},
            },
            "quote": {
                "source": "FIXTURE",
                "ltp": 509.0,
                "open": 507.0,
                "high": 510.0,
                "low": 503.5,
                "previous_close": 505.0,
                "bid": 508.5,
                "ask": 509.5,
                "bid_quantity": 2200,
                "ask_quantity": 2300,
                "volume": 11000,
                "traded_value": 5_599_000.0,
                "vwap": 508.0,
                "open_interest": 0,
                "change_in_oi": 0,
                "data_mode": "FIXTURE",
                "sequence_number": 112,
                "age_seconds": 4,
            },
        },
    ]

    quote_rows: List[Dict[str, Any]] = []
    mapping_rows: List[Dict[str, Any]] = []
    for listing in listings:
        quote = dict(listing.pop("quote"))
        mapping_payload = listing.pop("mappings")
        listing["source"] = "FIXTURE"
        for broker, broker_mapping in mapping_payload.items():
            mapping_rows.append(
                {
                    "broker": broker,
                    "last_verified_timestamp": _verified(now_utc, broker_mapping.pop("last_verified_age_hours", 0)) if broker_mapping else None,
                    **broker_mapping,
                    "symbol": listing["symbol"],
                    "exchange": listing["exchange"],
                    "segment": listing["segment"],
                }
            )
        quote_rows.append(
            {
                "symbol": listing["symbol"],
                "exchange": listing["exchange"],
                "segment": listing["segment"],
                "instrument_type": listing["instrument_type"],
                "timestamp_utc": _ts(now_utc, quote.pop("age_seconds", 0)),
                "received_at": _ts(now_utc, quote.get("age_seconds", 0)),
                **quote,
            }
        )

    payload = {"source": "FIXTURE", "source_version": FIXTURE_SOURCE_VERSION, "listings": listings, "mappings": mapping_rows, "quotes": quote_rows}
    payload["checksum"] = hashlib.sha256(json.dumps(payload, sort_keys=True, default=str).encode("utf-8")).hexdigest()
    return payload
